### ISSUE TITLE
Question about remote validation

### ISSUE THREAD

**Issue by codebury** [VeritasSoftware/ts.validator#1]
Hi!

How can I perform a remote validation, for example, to check if the Email is not already used making an http request (using async, promise or something like that)?

Thanks in advance.
Best regards.

**Comment by VeritasSoftware** [comment]
Async calls cannot be made as you want. 
The entire validation can be done Async but you cannot do part validations Async.

However, you could use the **Required rule** in which you make **Sync calls** (using "sync-request" npm package) to your API.

[**sync-request**](https://www.npmjs.com/package/sync-request)

Add sync-request to your project.

Then, you can create a typescript Sync **HttpService** like below:

```
import request from 'sync-request';

export class HttpService
{    
    get<TResponse>(url: string): TResponse {
        var res = request('GET', url);

        var body = res.getBody('utf8');

        var o = JSON.parse(body);

        return o;        
    }

    post<TRequest, TResponse>(url: string, req: TRequest) : TResponse {
        const options = {
            json: JSON.parse(JSON.stringify(req))
        };
        
        var res = request('POST', url, options);

        var body = res.getBody('utf8');

        var o = JSON.parse(body);

        return o;
    }
}
```
Then, in your **Required rule** call the Service like below: 

```
    .If(m => m.Email != "", validator =>
                                        validator.Required(m => m.Email, (m, email) => {
                                            var res = new HttpService().get<Response>("http://localhost:59039/api/Movies/validateEmail/"+ email);

                                            return res.isValid;
                                        }, "Email already present", "Email:AlreadyPresent")
                           .ToResult())
```

where **Response** (the response from the back end API) can be like below:

```
class Response
{
    isValid: boolean;
}
```

If you are using Angular 2+, you can mark the HttpService as @Injectable.
Then, you can inject it into the validation service.

**Comment by VeritasSoftware** [comment]
Hi,

I went ahead and created a npm package ts-sync-request for the sync http.

[**ts-sync-request**](https://www.npmjs.com/package/ts-sync-request)

This package contains the TypeScript strongly-typed wrapper for sync-request library that I have built.

## Sample usage

Install package in project:

    npm i ts-sync-request

Usage:

```
import { SyncRequestService } from 'ts-sync-request/dist'
```

```
    .If(m => m.Email != "", validator =>
                                        validator.Required(m => m.Email, (m, email) => {
                                            var res = new SyncRequestService().get<Response>("http://localhost:59039/api/Movies/validateEmail/"+ email);

                                            return res.isValid;
                                        }, "Email already present", "Email:AlreadyPresent")
                           .ToResult())
```

**Comment by codebury** [comment]
Hi,

Thanks for your quick response. I think using a sync http request solves the issue very well, at least in my case. Your work is much appreciated. I will close the issue if you don't mind.

Thank you very much.
Best regards.
