### ISSUE TITLE
Email validation not working

### ISSUE THREAD

**Issue by Ryukote** [VeritasSoftware/ts.validator#2]
Hi, I have an issue with Email validator. Here is the rule I have createad:

```typescript
export const emailRules = (validator: IValidator<string>): ValidationResult => {
  return validator
    .Email(x => x.toLowerCase(), validationConstants.email)
    .ToResult()
}
```
This is my test code:

```typescript
const assert = require("assert");

describe("Account form validations:", () => {
    it("will pass email validation", () => {
        let email = "test@something.com";

        let validationResult = new validation.Validator(email)
            .Validate(emailRules);
        
        assert.notEqual(validationResult, null);
        assert.notEqual(validationResult, undefined);
        assert.equal(validationResult.IsValid, true);
    })

    it("will fail email validation", () => {
        let email = "test@some";

        let validationResult = new validation.Validator(email)
            .Validate(rules.emailRules);
        
        assert.notEqual(validationResult, null);
        assert.notEqual(validationResult, undefined);
        assert.equal(validationResult.IsValid, false);
    })
});
```

In both cases I get an error: 

> "TypeError: Cannot assign to read only property '0' of string 'test@something.com'"

 and 

> "TypeError: Cannot assign to read only property '0' of string 'test@some'"

In the output it says that happen at

> ...\node_modules\ts.validator.fluent\dist\type-factory.js:41:29

Did I do something wrong or this is a bug?

**Comment by VeritasSoftware** [comment]
Hi,

Try removing .toLowerCase().
The rules are supposed to apply on a property.

**Comment by Ryukote** [comment]
I have. Now my rule looks like this:

```typescript
export const emailRules = (validator: IValidator<string>): ValidationResult => {
  return validator
    .Email(x => x, validationConstants.email)
    .ToResult()
}
```

and my test looks like this:

```typescript
describe("Account form validations:", () => {
    it("will pass email validation", () => {
        let email = "test@something.com";

        let validationResult = new validation.Validator(email)
            .Validate(emailRules);
        
        assert.notEqual(validationResult, null);
        assert.notEqual(validationResult, undefined);
        assert.equal(validationResult.IsValid, true);
    })

    it("will fail email validation", () => {
        let email = "test@some";

        let validationResult = new validation.Validator(email)
            .Validate(rules.emailRules);
        
        assert.notEqual(validationResult, null);
        assert.notEqual(validationResult, undefined);
        assert.equal(validationResult.IsValid, false);
    })
});
```
Both tests are failing with the same error message.

Plus, I have placed breakpoint in my rule and it is not even hitting it. It goes straight to

> \node_modules\ts.validator.fluent\dist\type-factory.js:41:29

With that error message.

**Comment by VeritasSoftware** [comment]
Yes, actually the rule is supposed to be around a property.

Eg. .Email(x => x.Email, "Should be valid email").

But, you can see if below works.

.Email(x => x, "Should be valid email", "Email")

**Comment by Ryukote** [comment]
I have tried bellow suggest. Still not working. So, basically, I would have to make an object which only contains one property "Email". Isn't that an overhead?

**Comment by VeritasSoftware** [comment]
This is meant to validate objects. Not primitives.
If you want to use this, you can easily encapsulate that into an object.

It should not be a problem at all.
