### ISSUE TITLE
validate dates will change time on input date object

### ISSUE THREAD

**Issue by me23** [VeritasSoftware/ts.validator#7]
I would like to validate an given Date-Attribute of my class. The Date hat a time set, after the validation
the time is set to 0.0.0.

Here is a short example :
```
const { IValidator, Validator, ValidationResult } = require( 'ts.validator.fluent/dist');

class Sut {
	myDate = new Date('2022-01-01T12:13:14.000Z');
}


let validateSuperRules =  (validator) => {
	   return validator
	         .IsDateAfter(m => m.myDate, new Date("1970-01-01T00:00:00.000Z"), "Should be after 1.1.1970", "Sut.myDate")
	         .ToResult();
};

const sut = new Sut();

console.log(sut.myDate);
const result = new Validator(sut).Validate(validateSuperRules);
console.log(result);
console.log(sut.myDate);
```

The Result (3x console.log) will be this: 
```
2022-01-01T12:13:14.000Z
ValidationResult { Errors: [], IsValid: true }
2021-12-31T23:00:00.000Z
```

I would expect that the validation will not change any values of the input-object.

I looked at the object-validator.ts code: On each Date-validation the first few lines is ` val.setHours(0, 0, 0, 0);` which cause the change.

edit:
I see this: 
```
var val = predicate(this._model);
 val.setHours(0, 0, 0, 0);
```
Shouldn't it be 
```
var val = predicate(this._clonedmodel);
 val.setHours(0, 0, 0, 0);
```
In the file object-validator.ts all instances of `var val = predicate(this._model)` should be changed, or be i wrong?

**Comment by VeritasSoftware** [comment]
The IsDateAfter method is designed, to only evaluate the date part.

If you do not want it's default behaviour, please use Required method
and do your custom validation there.
